name: Swaylend Indexer
ecosystem: fuel
networks:
        - id: 0
          start_block: 9495000
          contracts:
                  - name: Market
                    address: 0x13d310c91b06341f1a74b5258f12a84f0f1735269709f4919394579f53ecb717
                    abi_file_path: ./abi/market-abi.json
                    handler: ./src/EventHandlers.ts
                    events:
                            - name: CollateralAssetAdded
                            - name: CollateralAssetUpdated
                            - name: CollateralAssetPaused
                            - name: CollateralAssetResumed
                            - name: UserBasicEvent
                            - name: MarketBasicEvent
                            - name: UserSupplyCollateralEvent
                            - name: UserWithdrawCollateralEvent
                            - name: UserSupplyBaseEvent
                            - name: UserWithdrawBaseEvent
                            - name: AbsorbCollateralEvent
                            - name: UserLiquidatedEvent
                            - name: BuyCollateralEvent
                            - name: ReservesWithdrawnEvent
                            - name: PauseConfigurationEvent
                            - name: MarketConfigurationEvent
